- name: Install X server and xinit
  apt:
    name:
      - xserver-xorg
      - xinit
      - mesa-utils # For testing
    state: present
    install_recommends: no
    update_cache: yes
- name: Create desktop user
  user:
    name: "{{ desktop_user }}"
    comment: "Desktop User"
    create_home: yes
    shell: /bin/bash
    uid: 1001
    groups:
      - video
      - audio
      - input
      - plugdev
      - tty
    append: yes
- name: Create launch script
  copy:
    dest: /usr/local/bin/launch
    content: |
      #!/bin/bash
      set -e
      
      APP=${1:-glxgears}
      DISPLAY_NUMBER=${2:-1}
      
      echo "Starting $APP as desktop_user on X display :$DISPLAY_NUMBER"
      
      # Start a new VT and run X as desktop_user
      sudo -u desktop_user openvt -s -- xinit "$APP" -- :$DISPLAY_NUMBER
    owner: root
    group: root
    mode: "0755"
