- name: Install X server and xinit
  apt:
    name:
      - xserver-xorg
      - xinit
    state: present
    install_recommends: no
    update_cache: yes
- name: Create desktop user
  user:
    name: "{{ desktop_user }}"
    comment: "Desktop User"
    create_home: yes
    shell: /bin/bash
    uid: 1001
    groups:
      - video
      - audio
      - input
      - plugdev
    append: yes
- name: Create launch script
  copy:
    dest: /usr/local/bin/launch.sh
    content: |
      #!/bin/bash
      set -e
      APP=${1:-{{default_app}}}
      sudo systemctl isolate graphical.target
      sudo -u {{desktop_user}} xinit $APP -- :{{display_number}} vt$(fgconsole)
      sudo systemctl isolate multi-user.target
    owner: root
    group: root
    mode: "0755"
