- name: Ensure Snap is installed
  apt:
    name: snapd
    state: present
    update_cache: yes
- name: Install Steam snap (via command) # snap module is outdated
  command: snap install steam
  args:
    creates: /snap/steam
- name: Connect steam snap interfaces
  command: |
    snap connect steam:system-observe
    snap connect steam:hardware-observe
