#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - network
  identity:
    hostname: loungebox
    username: lounge
    password: $1$TFljfm/3$5UJ9LpAdVSCFjOyYA6DMp/ # password: lounge
  ssh:
    install-server: true
    allow-pw: true
  keyboard:
    layout: au
  locale: en_NZ.UTF-8
  timezone: Pacific/Auckland
  drivers:
    install: true
  storage:
    layout:
      name: direct
      match:
        type: nvme
      config:
        - type: disk
          id: nvme0n1
          wipe: superblock-recursive
          preserve: false
          partitions:
            - type: partition
              size: 30G
              fs-type: ext4
              mount-point: /
  packages:
    - git
    - nano
    - curl
  updates: all
  late-commands:
    # Enable SSH immediately
    - curtin in-target --target=/target -- systemctl enable ssh
    - curtin in-target --target=/target -- systemctl start ssh
    # Expire password to force change on first login
    - curtin in-target --target=/target -- chage -d 0 lounge
