all:
  hosts:
    loungebox:
      ansible_host: 192.168.205.3
      ansible_user: lounge
      array_devices:
        - /dev/disk/by-id/ata-WDC_WD40EFZX-68AWUN0_WD-WX22DC1L71ZC
        - /dev/disk/by-id/ata-WDC_WD40EFZX-68AWUN0_WD-WX32D12NL2JP
        - /dev/disk/by-id/ata-WDC_WD40EFZX-68AWUN0_WD-WX32DC1RKJTX
        - /dev/disk/by-id/ata-WDC_WD40EFZX-68AWUN0_WD-WXA2D91C1LEY
